Update V&V_request.md
biosensics/.github pull request #12
Opened 2021-11-17 17:00 UTC by MarcDerhammer

shuffled

2021-11-17 17:13 UTC, andrewalc requested changes

2021-11-17 17:13 UTC, andrewalc commented on .github/ISSUE_TEMPLATE/V&V_request.md
> +- [ ] Merge `release` branch into `master` on Application repository
```suggestion
- [ ] Merge `release` branch into `master` on server repository
- [ ] Merge `release` branch into `master` on Application repository
```

oh this should probably get added for the server repo as well

2021-11-18 18:35 UTC, andrewalc approved these changes

2021-11-18 18:48 UTC, abbylindsay approved these changes

2021-11-18 19:22 UTC, merged