Create New_feature_request.md
biosensics/.github pull request #30
Opened 2022-07-29 20:49 UTC by abbylindsay

2022-07-29 20:55 UTC, rcole1025 reviewed
What about tagging Kevin if already released?

2022-08-01 13:32 UTC, barchard requested changes

2022-08-01 13:32 UTC, barchard commented on .github/ISSUE_TEMPLATE/New_feature_request.md
> +labels:
We should add one of the existing labels that GitHub defines (e.g., `enhancement`)

2022-08-01 13:32 UTC, barchard commented on .github/ISSUE_TEMPLATE/New_feature_request.md
> +<!-- Is this simply a new feature or is this to resolve a different issue -->
if it's a problem, shouldn't we use the Bug template?

2022-08-01 13:32 UTC, barchard commented on .github/ISSUE_TEMPLATE/New_feature_request.md
> +**Priority level:**
Make this a dropdown?

2022-08-01 13:32 UTC, barchard commented on .github/ISSUE_TEMPLATE/New_feature_request.md
> +<!-- The more the better. -->
It may help to capture what component(s) this will touch (if known). Operations may not know so it may be something we determine.

2022-08-01 13:32 UTC, barchard commented on .github/ISSUE_TEMPLATE/New_feature_request.md
> +**Describe the work you would like completed:**
Required fields should be marked as required here to prevent users from omitting items.

2022-08-03 13:37 UTC, marcderhammer approved these changes

2022-08-09 14:29 UTC, merged