Update V&V_request.md
biosensics/.github pull request #9
Opened 2021-10-26 15:31 UTC by abbylindsay

sorry - i accidentally merged when trying to accept rylee's edits. please still review

2021-10-26 15:48 UTC, marcderhammer requested changes
Creating a parse account is an operations task

Edit: Nevermind you guys are right haha

2021-10-26 17:26 UTC, CindyDurkin reviewed
Under Operations, the last item is "Attach V&V PDF to this issue". I think this should either be taken right off QSR by Teresa or Quality should be attaching (if it is necessary to attach the template to be used). 

I think steps 50- & 51 should be Quality. The final step is Quality sends out a release notification. Maybe we should add that in here too. I'm not sure if that's necessary. Kevin can decide.

2021-10-27 17:27 UTC, barchard approved these changes

2021-10-27 17:55 UTC, CindyDurkin approved these changes

2021-10-29 14:02 UTC, KevinCarter0513 approved these changes

2021-10-29 14:39 UTC, rcole1025 approved these changes

2021-10-29 14:43 UTC, marcderhammer approved these changes

2021-10-29 15:13 UTC, teresaho-biosensics approved these changes

2021-10-29 15:14 UTC, ana-enriquez approved these changes

2021-10-29 15:17 UTC, merged